import 'package:flutter/widgets.dart';

class IconFontIcons {
    // IconFontIcons._();
    // static const String _family = 'IconFontIcons';
    static const IconData mq2AppShezhi = IconData(0xe612,fontFamily:'IconFontIcons');
    static const IconData mq2AppKucun = IconData(0xe611,fontFamily:'IconFontIcons');
    static const IconData mq2AppPandian = IconData(0xe615,fontFamily:'IconFontIcons');
    static const IconData mq2AppCaigoujihua = IconData(0xe614,fontFamily:'IconFontIcons');
    static const IconData mq2AppZhuisu = IconData(0xe616,fontFamily:'IconFontIcons');
    static const IconData mq2AppTiaobo = IconData(0xe617,fontFamily:'IconFontIcons');
    static const IconData mq2AppAishugangjin = IconData(0xe618,fontFamily:'IconFontIcons');
    static const IconData mq2AppSousuo1 = IconData(0xe619,fontFamily:'IconFontIcons');
    static const IconData mq2AppRukuguanli = IconData(0xe61c,fontFamily:'IconFontIcons');
    static const IconData mq2AppZhijinzhichu = IconData(0xe61b,fontFamily:'IconFontIcons');
    static const IconData mq2AppChukuguanli = IconData(0xe61a,fontFamily:'IconFontIcons');
    static const IconData mq2AppDingdan1 = IconData(0xe61d,fontFamily:'IconFontIcons');
    static const IconData mq2App31shijian = IconData(0xe600,fontFamily:'IconFontIcons');
    static const IconData mq2AppDanjuguanli = IconData(0xe6e2,fontFamily:'IconFontIcons');
    static const IconData mq2AppZengjia = IconData(0xe6ea,fontFamily:'IconFontIcons');
    static const IconData mq2AppIcon_jobs = IconData(0xe61e,fontFamily:'IconFontIcons');
    static const IconData mq2AppWushuju = IconData(0xe61f,fontFamily:'IconFontIcons');
    static const IconData mq2AppTuichu = IconData(0xe620,fontFamily:'IconFontIcons');
    static const IconData mq2AppXiangxia = IconData(0xe85d,fontFamily:'IconFontIcons');
    static const IconData mq2AppXiangyou1 = IconData(0xe775,fontFamily:'IconFontIcons');
    static const IconData mq2AppJiahao = IconData(0xe603,fontFamily:'IconFontIcons');
    static const IconData mq2AppShanchu = IconData(0xe718,fontFamily:'IconFontIcons');
    static const IconData mq2AppShanchu1 = IconData(0xe621,fontFamily:'IconFontIcons');
    static const IconData mq2App31guanbi = IconData(0xe601,fontFamily:'IconFontIcons',matchTextDirection: true);
    static const IconData mq2AppBianji = IconData(0xe602,fontFamily:'IconFontIcons');
    static const IconData mq2AppShanchu2 = IconData(0xe604,fontFamily:'IconFontIcons');
    static const IconData mq2AppZengjia1 = IconData(0xe8c8,fontFamily:'IconFontIcons');
    static const IconData mq2AppXiaoshudian1 = IconData(0xe738,fontFamily:'IconFontIcons');
    static const IconData mq2AppJia = IconData(0xe605,fontFamily:'IconFontIcons');
    static const IconData mq2AppAMethodDrawImage1 = IconData(0xe606,fontFamily:'IconFontIcons');
    static const IconData mq2AppDuigou = IconData(0xebe6,fontFamily:'IconFontIcons');
    static const IconData mq2AppShuxian = IconData(0xe607,fontFamily:'IconFontIcons');
    static const IconData mq2AppFujian = IconData(0xe88a,fontFamily:'IconFontIcons');
    static const IconData mq2AppBaoguo_hezi = IconData(0xeb2e,fontFamily:'IconFontIcons');
    static const IconData mq2AppCaidan = IconData(0xe622,fontFamily:'IconFontIcons');
    static const IconData mq2AppXiangshang = IconData(0xe608,fontFamily:'IconFontIcons');
    static const IconData mq2AppGongyingshangguanli = IconData(0xe623,fontFamily:'IconFontIcons');
    static const IconData mq2AppSaoma = IconData(0xe712,fontFamily:'IconFontIcons');
    static const IconData mq2AppWeibiaoti = IconData(0xe60f,fontFamily:'IconFontIcons');
    static const IconData mq2AppYewu_cheliangguobang = IconData(0xe631,fontFamily:'IconFontIcons');
    static const IconData mq2AppZhongjianchengzhong = IconData(0xe666,fontFamily:'IconFontIcons');
    static const IconData mq2AppCangpeitubiao_huanhuorukutuihuoruku = IconData(0xe610,fontFamily:'IconFontIcons');
    static const IconData mq2AppCangpeitubiao_chukuhuanhuochuku = IconData(0xe60b,fontFamily:'IconFontIcons');
    static const IconData mq2AppXiaofeimingxidan = IconData(0xe643,fontFamily:'IconFontIcons');
    static const IconData mq2AppRuwangcheliangshu = IconData(0xe609,fontFamily:'IconFontIcons');
    static const IconData mq2AppMingxi = IconData(0xe689,fontFamily:'IconFontIcons');
    static const IconData mq2AppDingdan = IconData(0xe737,fontFamily:'IconFontIcons');
    static const IconData mq2AppDanju = IconData(0xe60a,fontFamily:'IconFontIcons');
}